### ISSUE TITLE
java.lang.NoSuchMethodError: org.bukkit.entity.Entity.setCustomName(Ljava/lang/String;)V

### ISSUE THREAD

**Issue by satoshinm** [satoshinm/WebSandboxMC#15]
```
23:26:48 [INFO] userEventTriggered: HANDSHAKE_COMPLETE
23:26:48 [INFO] userEventTriggered: io.github.satoshinm.WebSandboxMC.dep.io.netty.handler.codec.http.websocketx.WebSocketServerProtocolHandler$HandshakeComplete@28997b0a
23:26:48 [WARNING] [WebSandboxMC] Task #34 for WebSandboxMC v0.2 generated an exception
java.lang.NoSuchMethodError: org.bukkit.entity.Entity.setCustomName(Ljava/lang/String;)V
	at io.github.satoshinm.WebSandboxMC.bridge.WebPlayerBridge.newPlayer(WebPlayerBridge.java:53)
	at io.github.satoshinm.WebSandboxMC.ws.WebSocketServerThread.handleNewClient(WebSocketServerThread.java:155)
	at io.github.satoshinm.WebSandboxMC.ws.WebSocketFrameHandler$1.run(WebSocketFrameHandler.java:58)
	at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftTask.run(CraftTask.java:58)
	at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:344)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:777)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:320)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:732)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:614)
	at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
23:26:48 [WARNING] [WebSandboxMC] Task #46 for WebSandboxMC v0.2 generated an exception
java.lang.NullPointerException
	at io.github.satoshinm.WebSandboxMC.bridge.WebPlayerBridge.clientMoved(WebPlayerBridge.java:76)
	at io.github.satoshinm.WebSandboxMC.ws.WebSocketServerThread.handle(WebSocketServerThread.java:205)
	at io.github.satoshinm.WebSandboxMC.ws.WebSocketFrameHandler$2.run(WebSocketFrameHandler.java:86)
	at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftTask.run(CraftTask.java:58)
	at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:344)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:777)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:320)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:732)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:614)
	at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
```

**Comment by satoshinm** [comment]
This can occur on older server software without this functionality, server owners can disable it in config.yml `entity_custom_names` and/or `entity_disable_gravity`, set to false, if this error occurs or they don't want it.
