### ISSUE TITLE
Include optimized NetCraft build with craft.html.mem

### ISSUE THREAD

**Issue by satoshinm** [satoshinm/WebSandboxMC#6]
Instead of the unoptimized version consisting only of craft.html and craft.js which is several times larger

**Comment by satoshinm** [comment]
Adding craft.html.mem to http, but there's a couple problems. The filtering matches lines to substitute the argv module arguments for the server's external address:

```java
            while ((line = reader.readLine()) != null) {
                if (line.equals("Module['arguments'] = argv;")) {
                    buffer.append("Module['arguments'] = ['" + ourExternalAddress + "', '" + ourExternalPort + "'];");
                    continue;
                }
```

kinda ugly, maybe can be improved. Would need to be for the optimized craft.js, which is all on one line. But even without it, NetCraft fails when served through this web server:

1
index.html:1251 1
printErr @ index.html:1251
abort @ craft.js:36
hz @ craft.js:25
ow @ craft.js:13
Uv @ craft.js:13
Rv @ craft.js:13
Qv @ craft.js:13
sx @ craft.js:25
ih @ craft.js:7
pg @ craft.js:7
callMain @ craft.js:36
doRun @ craft.js:36
(anonymous) @ craft.js:36
setTimeout (async)
run @ craft.js:36
runCaller @ craft.js:36
removeRunDependency @ craft.js:1
applyMemoryInitializer @ craft.js:36
useRequest @ craft.js:36
setTimeout (async)
(anonymous) @ craft.js:36
index.html:1251 exception thrown: abort(1) at Error
    at jsStackTrace (http://localhost:4081/craft.js:1:586436)
    at stackTrace (http://localhost:4081/craft.js:1:586607)
    at abort (http://localhost:4081/craft.js:36:7758)
    at Array.hz (http://localhost:4081/craft.js:25:78112)
    at ow (http://localhost:4081/craft.js:13:116289)
    at Uv (http://localhost:4081/craft.js:13:104241)
    at Rv (http://localhost:4081/craft.js:13:99340)
    at Qv (http://localhost:4081/craft.js:13:98109)
    at sx (http://localhost:4081/craft.js:25:33912)
    at ih (http://localhost:4081/craft.js:7:111474)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
printErr @ index.html:1251
callMain @ craft.js:36
doRun @ craft.js:36
(anonymous) @ craft.js:36
setTimeout (async)
run @ craft.js:36
runCaller @ craft.js:36
removeRunDependency @ craft.js:1
applyMemoryInitializer @ craft.js:36
useRequest @ craft.js:36
setTimeout (async)
(anonymous) @ craft.js:36

rebuilt with -s ASSERTIONS=1 to emcc but didn't appear to give much more information.

**Comment by satoshinm** [comment]
This error message is completely opaque to me, and -s ASSERTIONS=1 is disabled with optimized builds (-O1 or greater, which is only where this issue occurs), how to proceed further to see what is going on?

---

Compared localhost:4081/craft.html.mem versus src/main/resources/craft.html.mem, completely different. This code is corrupting the binary data, it isn't a textual string:

```java
        BufferedReader reader = new BufferedReader(new InputStreamReader(getClass().getResourceAsStream(name)));
        String line;
        StringBuffer buffer = new StringBuffer();
        if (prepend != null) buffer.append(prepend);
        while ((line = reader.readLine()) != null) {
            buffer.append(line);
            buffer.append('\n');
        }
```
