### ISSUE TITLE
error: java.lang.NoSuchMethodError: org.bukkit.entity.Entity.setGravity(Z)V

### ISSUE THREAD

**Issue by ghost** [satoshinm/WebSandboxMC#99]
https://pastebin.com/9RAS7DhF

**Comment by satoshinm** [comment]
@MineFriend try setting `entity_disable_gravity: false` in plugins/WebSandboxMC/config.yml, this will disable calling setGravity() since it is not available on 1.8:

```
Task #728 for WebSandboxMC v1.10.4 generated an exception
java.lang.NoSuchMethodError: org.bukkit.entity.Entity.setGravity(Z)V
        at io.github.satoshinm.WebSandboxMC.bridge.WebPlayerBridge.newPlayer(WebPlayerBridge.java:123) ~[?:?]
        at io.github.satoshinm.WebSandboxMC.ws.WebSocketServerThread.handleNewClient(WebSocketServerThread.java:161) ~[?:?]
        at io.github.satoshinm.WebSandboxMC.ws.WebSocketServerThread.handle(WebSocketServerThread.java:208) ~[?:?]
        at io.github.satoshinm.WebSandboxMC.ws.WebSocketFrameHandler$1.run(WebSocketFrameHandler.java:70) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```
